services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - .:/var/www/html
    # Add environment variables if needed
    # environment:
    #   - VARIABLE_NAME=value
